all:
  hosts:
    node1:
      ansible_host: 192.168.0.200
      ip: 192.168.0.200
      access_ip: 192.168.0.200
    node2:
      ansible_host: 192.168.0.201
      ip: 192.168.0.201
      access_ip: 192.168.0.201
    node3:
      ansible_host: 192.168.0.202
      ip: 192.168.0.202
      access_ip: 192.168.0.202

  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        # クラスター規模が小さいので3ノード全てで管理する
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
